### ISSUE TITLE
gulp tdd error

### ISSUE THREAD

**Issue by Frikki** [abiee/es6-marionette#2]
```
ERROR [config]: Invalid config file!
  Error: Cannot find module 'lodash'
```

**Comment by jesusx21** [comment]
npm install lodash or npm install

**Comment by Frikki** [comment]
`npm install` won’t cut it because there is no mention of `lodash` in `packages.json`. Also, `karma.conf.js` specifies files from the `bower_components` directory, though _jspm_ is used, not _bower_.

**Comment by abiee** [comment]
HI @Frikki,

I have made some changes at the code base. jspm was removed and you should not have any issues with the latest code on master branch.
