### ISSUE TITLE
gulp build doesn't work with fresh clone

### ISSUE THREAD

**Issue by connorblack** [abiee/es6-marionette#4]
Hi, looks like there are a few bugs with your build script. When freshly cloning the repo, running `gulp build` gets this error:

```
warn jspm_packages must be specified in the package.json within the baseURL for paths to resolve correctly.
     Building the single-file sfx bundle for main...

err  Error: ENOENT, open '/Users/connorblack/git/examples/es6-marionette/.tmp/scripts/main'
         at Error (native)
[16:47:14] 'bundle:app' errored after 1.71 s
[16:47:14] Error in plugin 'gulp-shell'
Message:
    Command `jspm bundle-sfx main dist/scripts/app.js --minify --skip-source-maps` failed with exit code 1
[16:47:14] 'build:app' errored after 14 s
[16:47:14] Error in plugin 'gulp-shell'
Message:
```

After changing line 109 from 

```
.pipe($.shell('jspm bundle-sfx main dist/scripts/app.js --minify --skip-source-maps'));
```

I thought changing it to the line below would fix the problem, but that opened up a whole can of worms:

```
.pipe($.shell('jspm bundle-sfx app dist/scripts/app.js --minify --skip-source-maps'));
```

**Comment by connorblack** [comment]
Also, for some reason, when changing `main` to `app` to get around the first bug, gulp looks two directories up for the `jspm_packages` folder when running `gulp build`!?

This is quite frustrating.

**Comment by abiee** [comment]
Hi Connor,

The project uses [jspm](http://jspm.io/) as package manager. Do you have it installed?

**Comment by gconaty** [comment]
jspm 0.15.7 works fine, but the latest 0.16.2 does not.

**Comment by abiee** [comment]
I will work on this weekend, I had work to do this week so, just give me some time

**Comment by abiee** [comment]
Hi @connorblack!

I have removed jspm from the project and use browserify instead. Take a look and tell me what do you think.
