### ISSUE TITLE
How do I define regions in a LayoutView?

### ISSUE THREAD

**Issue by davis** [abiee/es6-marionette#5]
I tried adding the following to the `constructor` call

```
this.regions = { test: '#test' }
```

and when i try to get the region it doesn't return anything

```
this.getRegion('test');
// => undefined
this.regionManager.length
// => 0
```

**Comment by abiee** [comment]
Backbone does not support full ES6 syntax at this moment, you should use another approach.

```
class MyView extends LayoutView {
  constructor() {
    // stuff
  }

  get regions() {
    return { test: '#test' };
  }
}
```

**Comment by davis** [comment]
ah got it. i had originally tried using marionette with es6 classes but went back to using .extend for this very reason. thanks though!
