### ISSUE TITLE
Backbone.radio shim not included?

### ISSUE THREAD

**Issue by tcosentino** [abiee/es6-marionette#8]
It mentions that the Backbone.radio shim is included, but I don't see it anywhere. Am I missing it somewhere? If not I can submit a PR adding it..

I get the error `cannot read property 'radio' of undefined` when running the app out of the box.

**Comment by abiee** [comment]
I'm working on an update of this repo, I will upgrade dependencies and this issue is includes. Maybe this weekend I finish the work. Will ping you when it's done. Anyway, if you want to submit a PR, go ahead I will appreciate it.

**Comment by tcosentino** [comment]
Thanks for the update. I added the shim and then ran into a problem with backbone.babysitter not initializing correctly. My compiled file had 3 different copies of backbone in it so I think that might be the cause. As I am new to gulp/browserify I couldn't figure out what was causing that and decided to move on.

Anyways, I ended up switching gears and sort of combining https://github.com/vigetlabs/gulp-starter and https://github.com/marionettejs/marionette-integrations/tree/master/browserify to achieve what I was looking for.

**Comment by catobus** [comment]
Marionette itself depends on Backbone 1.3.2, see its [package.json](https://github.com/marionettejs/backbone.marionette/blob/master/package.json). However the last version of Backbone is 1.3.3. As a result, current `package.json` in `es6-marionette` installs two different versions of backbone. 

I think you can remove `"backbone": "^1.2.3",` from dependencies as it brings a separate version of backbone. `"backbone.marionette": "^2.4.4"` in enough to install all the required dependencies for Marionette.

**Comment by abiee** [comment]
@catobus you are right, removing Backbone dependency makes this work as expected. The project was working with Node 4. I will send the changes ASAP. Thanks! Great job man.

**Comment by abiee** [comment]
@tcosentino and @catobus I just updated the repo, please make a test of it, and tell me if is working good for you

**Comment by catobus** [comment]
@abiee It works OK now. Thanks!
